[package]
name = "torque_nif"
# Must match @version in mix.exs — release.sh refuses to tag on a mismatch.
version = "0.2.7"
edition = "2021"

[lib]
name = "torque_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.36", features = ["big_integer"] }
sonic-rs = "0.5"
itoa = "1"
ryu = "1"
